# This is a basic workflow that is manually triggered

name: post to x

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
# on: [push, pull_request]
on:  
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Message'
        # Default value if no value is explicitly provided
        default: 'test from gha'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # preview:
  #   name: Preview
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request'
  #   steps:
  #     - uses: twitter-together/action@v3
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: nearform-actions/github-action-notify-twitter@v1.2.2
        with:
          message: "${{ github.event.inputs.description }}" #|
            # ${{ github.event.repository.name }} ${{ github.event.release.tag_name }} has been released. Check out the release notes: ${{ github.event.release.html_url }}
          twitter-app-key: ${{ secrets.TWITTER_API_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    
      # - uses: ethomson/send-tweet-action@v1
      #   with:
      #     status: "hard coded tweet" #${{ github.event.inputs.description }}
      #     consumer-key: ${{ secrets.TWITTER_API_KEY }}
      #     consumer-secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
      #     access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      #     access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          
  # tweet:
  #   name: Tweet
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout main
  #       uses: actions/checkout@v3
  #     - name: Tweet
  #       uses: twitter-together/action@v3
  #       with:
  #         tweet: ${{ github.event.inputs.description }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  #         TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  #         TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
  #         TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
