# This is a basic workflow that is manually triggered

name: post to x

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]
# on:  
#   workflow_dispatch:
#     # Inputs the workflow accepts.
#     inputs:
#       name:
#         # Friendly description to be shown in the UI instead of 'name'
#         description: 'Message'
#         # Default value if no value is explicitly provided
#         default: 'test from gha'
#         # Input has to be provided for the workflow to run
#         required: true
#         # The data type of the input
#         type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: twitter-together/action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v3
      - name: Tweet
        uses: twitter-together/action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
